apiVersion: v1
kind: Deployment
metadata:
  name: dogs
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - name: dogs
        image: localhost:5000/posalabs/dogs:latest
        ports:
        - containerPort: 8080