apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogs-deployment
  labels:
    app: dogs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - name: dogs
        image: localhost:5000/posalabs/dogs:latest
        ports:
        - containerPort: 8090